### ISSUE TITLE
Choclatey reporting wrong new version

### ISSUE THREAD

**Issue by dcmouser** [Absoblogginlutely/Chocolatey-Screenshotcaptor#3]
Choclatey is reporting a new version, v5, of Screenshot Captor being available.
But the current real version is 4.29.

**Comment by Absoblogginlutely** [comment]
Hi @dcmouser , Apologies for the delay - not sure where my email came in on this.  The original chocolatey version before I took over was already way ahead of the version that you had from the April version. In order to keep instep and force updates to the new version I made the version 5 and then the rest of the version number is the date of release for your software. So the new version you released on the 7th will be 5.0.0.2018120700  This enables me to run patches if something goes wrong with the build as I can just increase the last two numbers without breaking the release date.
